[update]
tasks = ["interfaces", "code", "normalize"]

[update.interfaces]
path = "./LyricsX"
defaultToBase = true
ignoreEmptyStrings = false
unstripped = false

[update.code]
codePath = "./LyricsX"
localizablePath = "./LyricsX/Supporting Files"
defaultToKeys = false
additive = true
unstripped = false

[update.transform]
codePath = "./LyricsX"
localizablePath = "./LyricsX/Supporting Files"
transformer = "foundation"
supportedLanguageEnumPath = "."
typeName = "BartyCrouch"
translateMethodName = "translate"

[update.normalize]
path = "./LyricsX"
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = true

[lint]
path = "."
duplicateKeys = true
emptyValues = true
